/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AsyncNotebook: typeof import('./src/components/async/AsyncNotebook.vue')['default']
    CenteredSpin: typeof import('./src/components/CenteredSpin.vue')['default']
    ConfirmDelete: typeof import('./src/components/popovers/ConfirmDelete.vue')['default']
    CreateNotebookModal: typeof import('./src/components/CreateNotebookModal.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    Note: typeof import('./src/components/Note.vue')['default']
    Notebook: typeof import('./src/components/Notebook.vue')['default']
    NotesTopPart: typeof import('./src/components/NotesTopPart.vue')['default']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopover: typeof import('naive-ui')['NPopover']
    NResult: typeof import('naive-ui')['NResult']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    PaddingWrapper: typeof import('./src/components/PaddingWrapper.vue')['default']
    ProfileMenu: typeof import('./src/components/ProfileMenu.vue')['default']
    RegisterForm: typeof import('./src/components/RegisterForm.vue')['default']
    RenameNotebook: typeof import('./src/components/popovers/RenameNotebook.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    TopPart: typeof import('./src/components/TopPart.vue')['default']
  }
}
